### ISSUE TITLE
Complicated app! 

### ISSUE THREAD

**Issue by brookeangel** [jordanburk/comicka#2]
It looks like it would be super cool, just make sure to build it up in slices. It's very easy to underestimate the time that it takes to build and _properly style_ these components - always better to be on the safe side. I would definitely start with the upload feature/ view for a single comic book before moving on to "index", "profile", "bookshelf" or "search".

Give yourself at least two days for the new/edit page and two days for the read comic pages. This will mean pushing some of your other features to the bonus. I really do think that styling these two key features will take a long time if done properly. If you do finish early, awesome! Better safe than sorry. Let me know how you feel about these suggestions.

**Comment by audreyburk** [comment]
Okay! I changed some things, AKA all the things.
I thought this was gonna be so much simpler before I started sketching out the whole proposal >_<

It's super hard for me to think how long any of this will take, so please, if you have any further specific suggestions, let me know. I think I've listed my tasks in a more reasonable order now, at least?

Thanks for all your time and feedback! It's super appreciated.

PS: Am I supposed to be closing issues, or am I supposed to let you know when I think I've fixed them, and you close them if I actually have? I've never used git issues before...

**Comment by brookeangel** [comment]
"Please please just let me sleep!" - accurate

**Comment by brookeangel** [comment]
Looks good! =D
